### ISSUE TITLE
[BUG] Worker failed to boot

### ISSUE THREAD

**Issue by Hampusm** [rmountjoy92/DashMachine#159]
**Operating system:** Debian 10 Buster
**Docker version:** 19.03.8, build afacb8b7f0
**Dashmachine version:** latest

Dashmachine is running in docker. Here's the relevant part of my docker-compose:
```
dashmachine:
    image: rmountjoy/dashmachine:latest
    restart: unless-stopped
    volumes:
      - dashmachine-userdata:/dashmachine/dashmachine/user_data
    environment:
      - VIRTUAL_HOST=dashboard.(domain)
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=dashboard.(domain)
      - LETSENCRYPT_EMAIL=(email address)
    networks:
      - proxy-tier
      - default
```

**Expected behaviour:**
For it to work. It did a couple of days ago with exactly the same docker-compose.

**Actual behaviour:**
I get a huge error message 
https://pastebin.com/7GqA8t5Z
