### ISSUE TITLE
Raspberrypi4 Using Portainer and Portainer Script

### ISSUE THREAD

**Issue by OpsKern** [rmountjoy92/DashMachine#209]
When I deploy DashMachine via either a portainer script or from the CLI, portainer sees TCP 5000 exposed for a few seconds after mounting the container successfully and then shortly afterward, the port is no longer exposed.

Here's the portainer script
```
---
version: "2"
services:
  dashmachine:
    image: rmountjoy/dashmachine:latest
    container_name: dashmachine
    volumes:
      - /mnt/USB01/dashmachine/user_data:/dashmachine/dashmachine/user_data
    ports:
      - 5000:5000
    restart: unless-stopped
```
Is this because the image I'm pulling isn't compatible with the ARM architecture?
Thank you.
