### ISSUE TITLE
CONTEXT_PATH Subfolder Error

### ISSUE THREAD

**Issue by vhenata** [rmountjoy92/DashMachine#39]
I am unable to get the page to load when trying to use a subfolder. Works perfectly fine without it.

This is my compose configuration
```
dashmachine:
        volumes:
            - ./dashmachine/user_data:/dashmachine/dashmachine/user_data
        environment:
            CONTEXT_PATH: /dash
        ports:
            - 5001:5000
        restart: unless-stopped
        image: rmountjoy/dashmachine:latest
```
I have attached the error output when I try to browse  to the page with this config. Is there anything I'm doing wrong?

[subfolder_error_log.txt](https://github.com/rmountjoy92/DashMachine/files/4349094/subfolder_error_log.txt)

**Comment by di-dc** [comment]
Not sure if they matter (can't test right now) but for reference my docker-compose has two small differences from yours -- a dash before "CONTEXT_PATH", and no space after the equal sign:

```
  dashmachine:
    container_name: dashmachine
    image: rmountjoy/dashmachine:latest
    restart: unless-stopped
    environment:
      - CONTEXT_PATH=/dash
    volumes:
      - path\to\dashmachine\config\folder:/dashmachine/dashmachine/user_data
    ports:
      - 5000:5000
```

**Comment by vhenata** [comment]
Thanks for the reply. I changed my compose to the following

```
    dashmachine:
        volumes:
            - ./dashmachine/user_data:/dashmachine/dashmachine/user_data
        environment:
            - CONTEXT_PATH=/dash
        ports:
            - 5001:5000
        restart: unless-stopped
        image: rmountjoy/dashmachine:latest   
```
Still behaves the same
